// Local Playwright / installed Chrome fallback; no browser MCP is available.
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { AlgoUsers, loadAlgoAuthConfig } from '../dist/src/algo/auth.js';
import { startAlgo } from '../dist/src/algo/server.js';
import { createEdgeRuntime } from '../dist/src/edge/composition-root.js';
import { DEFAULT_NODE_LIMITS } from '../dist/src/edge/config.js';
import { buildRegistry } from '../dist/src/edge/registry.js';
import { KEY, nodesJson, siteJson } from '../dist/test/fixtures.js';

const artifacts = resolve(process.env.ACCOUNT_ARTIFACT_DIR ?? '../.codex/docs/algo-admin-improvements/task-2-2-account-management/artifacts');
mkdirSync(artifacts, { recursive: true });
const dataDir = mkdtempSync(join(tmpdir(), 'tm-account-browser-')), usersPath = join(dataDir, 'users.json'), password = randomBytes(18).toString('hex');
process.env.DATA_DIR = dataDir;
const users = new AlgoUsers(usersPath);
for (const [name, role] of [['admin', 'admin'], ['backup', 'admin'], ['viewer', 'viewer'], ['engineer', 'engineer'], ['operator', 'operator']]) await users.add(name, password, role);
const cfg = { edgeId: 'accounts-test', keys: [KEY], allowUnsigned: false, udpPort: 0, udpHost: '127.0.0.1', sitePath: '', nodesPath: '', dataDir, recordRaw: false, consolePort: 0, algoPort: 0, consoleHost: '127.0.0.1', adminPassword: 'test-only', flashToken: null, pushUrls: [], pushToken: '', publishMs: 60000, gatewayPort: 0, gatewayToken: null, nodeHost: '127.0.0.1', nodePort: 0, nodeLimits: DEFAULT_NODE_LIMITS, nodeTls: null };
const runtime = createEdgeRuntime(cfg, buildRegistry(siteJson(), nodesJson()));
const handle = startAlgo(runtime, 0, '127.0.0.1', loadAlgoAuthConfig({ SESSION_SECRET: randomBytes(32).toString('hex'), ALGO_USERS_FILE: usersPath }, cfg.adminPassword));
await new Promise((done) => handle.server.once('listening', done));
const base = `http://127.0.0.1:${handle.server.address().port}`, browser = await chromium.launch({ headless: true, channel: 'chrome' });
const evidence = [], errors = [];
const login = async (context, username) => { assert.equal((await context.request.post(`${base}/auth/login`, { data: { username, password } })).status(), 200); };
try {
  for (const name of ['viewer', 'operator', 'engineer']) {
    const context = await browser.newContext(); await login(context, name); const page = await context.newPage();
    await page.goto(`${base}/accounts`); await page.getByText('Admin access required.', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'Create account', exact: true }).count(), 0);
    assert.equal((await context.request.get(`${base}/api/admin/accounts`)).status(), 403);
    evidence.push(`${name}: direct page/API denied`); await context.close();
  }
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } }); await login(context, 'admin');
  for (const data of ['{bad', JSON.stringify({ password: 'x'.repeat(9000) })]) {
    const response = await context.request.post(`${base}/api/admin/accounts`, { data, headers: { 'content-type': 'application/json', 'x-tm-algo': '1' } });
    assert.equal(response.status(), 400); assert.equal((await response.json()).error.code, 'VALIDATION');
  }
  const page = await context.newPage(); page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`${base}/accounts`); await page.getByRole('button', { name: 'Manage viewer', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByLabel('Username', { exact: true }).fill('created-account');
  await page.getByLabel('New password', { exact: true }).fill(password); await page.getByLabel('Confirm password', { exact: true }).fill(password);
  await page.locator('form').getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByText('Account created-account saved.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Manage created-account', exact: true }).click();
  assert.equal(await page.getByLabel('Username', { exact: true }).getAttribute('readonly'), '');
  assert.equal(await page.getByLabel('Role', { exact: true }).inputValue(), 'operator');
  await page.getByLabel('Role', { exact: true }).selectOption('viewer');
  await page.getByRole('button', { name: 'Review role / status change' }).click();
  await page.getByText('This ends current sessions. Submitted training jobs continue.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Cancel action' }).click();
  assert.equal(users.get('created-account').role, 'operator');
  await page.getByRole('button', { name: 'Review role / status change' }).click(); await page.getByRole('button', { name: 'Confirm action' }).click();
  await page.locator('#account-editor-heading').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Manage created-account' }).waitFor();
  await page.getByRole('button', { name: 'Manage created-account' }).click();
  assert.equal(await page.getByLabel('Role', { exact: true }).inputValue(), 'viewer');
  await page.getByLabel('Enabled', { exact: true }).uncheck(); await page.getByRole('button', { name: 'Review role / status change' }).click(); await page.getByRole('button', { name: 'Confirm action' }).click();
  await page.locator('#account-editor-heading').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Manage created-account' }).waitFor();
  assert.equal(users.get('created-account').disabled, true);
  await page.getByRole('button', { name: 'Manage created-account' }).click();
  users.update('created-account', { revoke: true });
  await page.getByLabel('Enabled', { exact: true }).check(); await page.getByRole('button', { name: 'Review role / status change' }).click(); await page.getByRole('button', { name: 'Confirm action' }).click();
  await page.getByText('This account changed. Refresh before saving.', { exact: true }).waitFor();
  assert.equal(users.get('created-account').disabled, true);
  await page.getByRole('button', { name: 'Refresh accounts' }).click();
  await page.getByRole('button', { name: 'Manage created-account' }).waitFor(); await page.getByRole('button', { name: 'Manage created-account' }).click();
  await page.getByLabel('Enabled', { exact: true }).check(); await page.getByRole('button', { name: 'Review role / status change' }).click(); await page.getByRole('button', { name: 'Confirm action' }).click();
  await page.locator('#account-editor-heading').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Manage created-account' }).click();
  assert.equal(users.get('created-account').disabled, false);
  await page.getByLabel('New password', { exact: true }).fill('replacement password'); await page.getByLabel('Confirm password', { exact: true }).fill('replacement password');
  await page.getByRole('button', { name: 'Reset password', exact: true }).click(); await page.getByRole('button', { name: 'Confirm action' }).click();
  await page.locator('#account-editor-heading').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Manage created-account' }).waitFor();
  await page.getByRole('button', { name: 'Manage created-account' }).click(); assert.equal(await page.getByLabel('New password', { exact: true }).inputValue(), '');
  assert.equal(await users.verify('created-account', 'replacement password'), 'created-account');
  await page.getByRole('button', { name: 'Cancel editor' }).click();
  await page.setViewportSize({ width: 360, height: 800 });
  await page.getByRole('button', { name: 'Manage viewer' }).click();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.ok(await page.locator('caption').evaluate((element) => element.getBoundingClientRect().width > 200));
  assert.equal(await page.getByRole('link', { name: 'Accounts', exact: true }).last().isVisible(), true);
  const shortcut = await page.getByRole('link', { name: 'Accounts', exact: true }).last().boundingBox(), signOut = await page.getByRole('button', { name: 'Sign out' }).boundingBox();
  assert.ok(shortcut.x + shortcut.width <= signOut.x, 'mobile Accounts link and sign out do not overlap');
  await page.screenshot({ path: join(artifacts, 'accounts-mobile.png'), fullPage: true });
  await page.getByLabel('New password', { exact: true }).fill(password); await page.getByRole('button', { name: 'Cancel editor' }).click();
  await page.getByRole('button', { name: 'Manage viewer' }).click(); assert.equal(await page.getByLabel('New password', { exact: true }).inputValue(), '');
  await page.getByRole('button', { name: 'Cancel editor' }).click();
  users.update('backup', { disabled: true });
  await page.getByRole('button', { name: 'Manage admin' }).click(); await page.getByLabel('Role', { exact: true }).selectOption('viewer');
  await page.getByRole('button', { name: 'Review role / status change' }).click(); await page.getByRole('button', { name: 'Confirm action' }).click();
  await page.getByText('Keep at least one enabled admin.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Cancel editor' }).click();
  await page.getByRole('button', { name: 'Manage admin' }).click(); await page.getByRole('button', { name: 'Revoke all sessions' }).click(); await page.getByRole('button', { name: 'Confirm action' }).click();
  await page.waitForURL('**/login**'); await page.getByText('Your session ended. Sign in again.', { exact: true }).waitFor();
  evidence.push('admin: create, role/status confirmation, cancellation, stale edit, reset, mobile and self-revoke passed');
  assert.deepEqual(errors, []); await context.close();
  writeFileSync(join(artifacts, 'browser-results.json'), JSON.stringify({ runner: 'local Playwright / Chrome', evidence, pageErrors: errors }, null, 2));
  process.stdout.write('Account browser acceptance passed.\n');
} finally { await browser.close(); await handle.dispose(); await new Promise((done) => handle.server.close(done)); await runtime.stop(); }
