// Local installed Chrome/Playwright fallback; no browser MCP available.
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { AlgoUsers, loadAlgoAuthConfig } from '../dist/src/algo/auth.js';
import { startAlgo } from '../dist/src/algo/server.js';
import { createEdgeRuntime } from '../dist/src/edge/composition-root.js';
import { DEFAULT_NODE_LIMITS } from '../dist/src/edge/config.js';
import { buildRegistry } from '../dist/src/edge/registry.js';
import { KEY, nodesJson, siteJson } from '../dist/test/fixtures.js';

const artifacts = resolve(process.env.NOTIFICATION_ARTIFACT_DIR ?? '../.codex/docs/algo-admin-improvements/task-3-3-in-app-notifications/artifacts'); mkdirSync(artifacts, { recursive: true });
const dataDir = mkdtempSync(join(tmpdir(), 'tm-notify-browser-')), usersPath = join(dataDir, 'users.json'); process.env.DATA_DIR = dataDir;
const users = new AlgoUsers(usersPath), password = randomBytes(18).toString('hex');
for (const [name, role] of [['alice', 'viewer'], ['bob', 'admin']]) await users.add(name, password, role);
const at = Date.now() - 2000;
const job = (user, index) => ({ id: randomUUID(), user, status: 'COMPLETED', createdAt: at, updatedAt: at, endedAt: at, submittedAt: at, startedAt: at, spec: { name: `${user} history ${index}`, partition: 'cpu', cpusPerTask: 1, memGb: 1, gpus: 0, timeLimit: '1:00:00', modules: [], condaEnv: null, entrypoint: 'PRIVATE', args: [], env: {}, notifyEmail: false }, code: { kind: 'py', filename: 'PRIVATE', bytes: 0, sha256: 'PRIVATE', unpackedBytes: 0, fileCount: 0, py: [] }, sbatch: 'PRIVATE', lastPolledAt: at, slurmJobId: null, remoteDir: 'PRIVATE', exitCode: 0, slurmState: 'COMPLETED', elapsedSeconds: 1, node: 'PRIVATE', message: 'PRIVATE' });
const trainDir = join(dataDir, 'algo', 'train'); mkdirSync(trainDir, { recursive: true }); writeFileSync(join(trainDir, 'jobs.json'), JSON.stringify([...Array.from({ length: 25 }, (_, index) => job('alice', index)), job('bob', 0)]));
const cfg = { edgeId: 'notification-test', keys: [KEY], allowUnsigned: false, udpPort: 0, udpHost: '127.0.0.1', sitePath: '', nodesPath: '', dataDir, recordRaw: false, consolePort: 0, algoPort: 0, consoleHost: '127.0.0.1', adminPassword: 'test-only', flashToken: null, pushUrls: [], pushToken: '', publishMs: 60000, gatewayPort: 0, gatewayToken: null, nodeHost: '127.0.0.1', nodePort: 0, nodeLimits: DEFAULT_NODE_LIMITS, nodeTls: null };
const runtime = createEdgeRuntime(cfg, buildRegistry(siteJson(), nodesJson()));
runtime.rollouts.restore(null, [{ id: 'retained-rollout', buildId: 'build', version: 'Shared firmware', stage: 'stopped', startedAt: at, finishedAt: at, startedBy: 'console', target: { kind: 'all' }, note: 'PRIVATE', nodes: [] }]);
const handle = startAlgo(runtime, 0, '127.0.0.1', loadAlgoAuthConfig({ SESSION_SECRET: randomBytes(32).toString('hex'), ALGO_USERS_FILE: usersPath }, cfg.adminPassword));
await new Promise((done) => handle.server.once('listening', done));
const base = `http://127.0.0.1:${handle.server.address().port}`, browser = await chromium.launch({ headless: true, channel: 'chrome' });
const evidence = [], errors = [];
const login = async (context, username) => assert.equal((await context.request.post(`${base}/auth/login`, { data: { username, password } })).status(), 200);
try {
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } }); await login(context, 'alice');
  const actual = await context.request.get(`${base}/api/admin/notifications?owner=bob`); assert.equal(actual.status(), 200); const alice = (await actual.json()).data;
  assert.equal(alice.items.filter((item) => item.kind === 'training').length, 25); assert.equal(alice.items.filter((item) => item.kind === 'firmware').length, 1);
  assert.ok(!JSON.stringify(alice).includes('bob history')); assert.ok(!JSON.stringify(alice).includes('PRIVATE'));
  await login(context, 'bob'); const bob = (await (await context.request.get(`${base}/api/admin/notifications?owner=alice`)).json()).data; assert.equal(bob.items.filter((item) => item.kind === 'training').length, 1);
  await login(context, 'alice');
  const page = await context.newPage(); page.on('pageerror', (error) => errors.push(error.message));
  let snapshot = { ...alice, items: [], sources: Object.fromEntries(Object.keys(alice.sources).map((kind) => [kind, 'unavailable'])) }, mode = 'ok', reads = 0, peak = 0;
  const active = new Set(); page.on('request', (request) => { if (request.url().endsWith('/api/admin/notifications')) { active.add(request); peak = Math.max(peak, active.size); reads++; } });
  page.on('requestfinished', (request) => active.delete(request)); page.on('requestfailed', (request) => active.delete(request));
  await page.route('**/api/admin/notifications', async (route) => { if (mode === 'hang') return; await route.fulfill({ status: mode === 'error' ? 503 : 200, contentType: 'application/json', body: JSON.stringify({ data: mode === 'error' ? null : snapshot, error: mode === 'error' ? { code: 'UNAVAILABLE', message: 'Unavailable' } : null }) }); });
  await page.addInitScript(() => { window.notificationToasts = []; let last = ''; new MutationObserver(() => { const text = document.querySelector('.cx-toast')?.textContent ?? ''; if (text && text !== last) window.notificationToasts.push(text); last = text; }).observe(document, { childList: true, subtree: true, characterData: true }); });
  await page.goto(base); await page.getByRole('button', { name: /Notifications/ }).click();
  await page.getByRole('button', { name: 'Notifications, unread count unavailable', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Retry notifications', exact: true }).waitFor();
  assert.equal(await page.getByText('No alerts.', { exact: true }).count(), 0);
  assert.equal(await page.getByRole('heading', { name: 'System status', exact: true }).count(), 0);
  assert.equal(await page.locator('#notification-toggle svg').count(), 1);
  assert.deepEqual(await page.evaluate(() => window.notificationToasts), []);
  const poll = async () => { await Promise.all([page.waitForResponse((response) => response.url().endsWith('/api/admin/notifications')), page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')))]); await page.waitForTimeout(100); };
  snapshot = { ...alice, items: alice.items.filter((item) => item.kind !== 'training'), sources: { ...alice.sources, training: 'unavailable' } }; await poll();
  await page.getByRole('button', { name: 'Notifications, unread count unavailable', exact: true }).waitFor();
  snapshot = alice; await poll(); await page.getByRole('heading', { name: 'alice history 0', exact: true }).waitFor();
  assert.deepEqual(await page.evaluate(() => window.notificationToasts), [], 'first available source establishes a silent baseline');
  await page.getByRole('button', { name: 'Mark all as read', exact: true }).click(); await poll();
  assert.equal(await page.getByText('Unread', { exact: true }).count(), 0);
  const next = { id: 'training:new:Failed:100', kind: 'training', resourceId: 'new', label: 'New failed job', outcome: 'Failed', occurredAt: Date.now(), href: '/train?job=new' };
  snapshot = { ...alice, items: [next, ...alice.items] }; await poll(); await page.getByText('New failed job: Failed', { exact: false }).waitFor();
  await poll(); assert.equal((await page.evaluate(() => window.notificationToasts)).filter((text) => text.includes('New failed job: Failed')).length, 1);
  mode = 'error'; await poll(); await page.getByText('Could not refresh notifications.', { exact: false }).waitFor(); await page.getByRole('heading', { name: 'New failed job', exact: true }).waitFor();
  mode = 'ok'; await page.getByRole('button', { name: 'Retry notifications' }).click(); await page.waitForTimeout(200);
  assert.equal((await page.evaluate(() => window.notificationToasts)).filter((text) => text.includes('New failed job: Failed')).length, 1);
  await page.reload(); await page.getByRole('button', { name: /Notifications/ }).click(); await page.getByRole('heading', { name: 'New failed job', exact: true }).waitFor();
  assert.deepEqual(await page.evaluate(() => window.notificationToasts), [], 'reload history is silent');
  assert.ok(await page.getByText('Read', { exact: true }).count() >= 26);
  await page.setViewportSize({ width: 360, height: 800 }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await page.screenshot({ path: join(artifacts, 'notification-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: 'Close notifications' }).click(); assert.equal(await page.getByRole('button', { name: /Notifications/ }).evaluate((button) => document.activeElement === button), true);
  await page.keyboard.press('Enter'); await page.getByRole('heading', { name: 'Notifications', exact: true }).waitFor();
  await page.setViewportSize({ width: 1280, height: 900 }); await page.evaluate(() => { document.body.style.zoom = '2'; }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: join(artifacts, 'notification-zoom-200.png'), fullPage: true }); await page.evaluate(() => { document.body.style.zoom = ''; });
  if (!process.env.NOTIFICATION_LAYOUT_ONLY) {
  mode = 'hang'; await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange'))); await page.waitForTimeout(300);
  const heldReads = reads; await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange'))); await page.waitForTimeout(300); assert.equal(reads, heldReads);
  await page.getByText('Could not refresh notifications.', { exact: false }).waitFor({ timeout: 12000 });
  mode = 'ok'; await page.getByRole('button', { name: 'Retry notifications' }).click(); await page.waitForTimeout(200); assert.ok(reads > heldReads); assert.equal(peak, 1);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')); }); const hiddenReads = reads;
  await page.waitForTimeout(15500); assert.equal(reads, hiddenReads); await page.evaluate(() => { delete document.hidden; document.dispatchEvent(new Event('visibilitychange')); }); await page.waitForTimeout(200);
  }
  await page.getByRole('button', { name: 'Sign out' }).click(); await page.waitForURL('**/login**'); assert.equal(await page.getByRole('heading', { name: 'New failed job' }).count(), 0);
  await login(context, 'bob'); snapshot = bob; await page.goto(base); await page.getByRole('button', { name: /Notifications/ }).click(); await page.getByRole('heading', { name: 'bob history 0', exact: true }).waitFor(); assert.equal(await page.getByRole('heading', { name: /alice history/ }).count(), 0); assert.deepEqual(await page.evaluate(() => window.notificationToasts), []);
  evidence.push({ realOwnerTrainingCounts: [25, 1], fullSourceNotHealthSubset: true, layoutOnly: !!process.env.NOTIFICATION_LAYOUT_ONLY, checks: ['source-recovery silent baseline', 'new ID once', 'repeat/reconnect/reload no replay', 'read persistence', '360px and200% zoom', 'keyboard close/open', ...(!process.env.NOTIFICATION_LAYOUT_ONLY ? ['hung fetch10s abort/retry', 'single-flight and hidden15sec pause'] : []), 'logout/user switch privacy'], peakRequests: peak });
  await context.close();
  const blocked = await browser.newContext(); await blocked.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get: () => { throw new Error('blocked'); } }); }); await login(blocked, 'alice');
  const memory = await blocked.newPage(); await memory.goto(base); await memory.getByRole('button', { name: /Notifications/ }).click(); await memory.getByText('Read status cannot be saved in this browser.', { exact: true }).waitFor(); await memory.getByRole('button', { name: 'Mark all as read' }).click(); assert.equal(await memory.getByText('Unread', { exact: true }).count(), 0); await blocked.close();
  assert.deepEqual(errors, []); evidence.push('blocked storage uses in-memory read state');
  writeFileSync(join(artifacts, process.env.NOTIFICATION_LAYOUT_ONLY ? 'layout-results.json' : 'browser-results.json'), JSON.stringify({ runner: 'local Playwright / installed Chrome', evidence, pageErrors: errors }, null, 2)); process.stdout.write('Notification browser acceptance passed.\n');
} finally { await browser.close(); await handle.dispose(); await new Promise((done) => handle.server.close(done)); await runtime.stop(); }
